imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        enabled: false
    csrf_protection:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test:
    cache_sqlite_db: true

doctrine:
    dbal:
        driver: pdo_sqlite
        path: %kernel.cache_dir%/test.db
security:
    encoders:
        Sancho\AppBundle\Entity\User: sha1
