security:
    encoders:
        Sancho\AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 15
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Sancho\AppBundle\Entity\User, property: email }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: sancho_app_session_check
                login_path: sancho_app_session_new
                success_handler: sancho_app.handler.authentication_handler
            remember_me:
                key: %secret%
                lifetime: 31536000
                path: /
                domain: ~
                always_remember_me: true
            logout:
                path:   sancho_app_session_delete
                target: sancho_app_home

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
