services:
    extension.listener:
        class: Sancho\App\Bundle\Listener\DoctrineExtensionListener
        calls:
            - [ setContainer, [ @service_container ] ]

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
