sancho_app_home:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'SanchoAppBundle:StaticPages:home.html.twig'

sancho_app_help:
    path: /help
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'SanchoAppBundle:StaticPages:help.html.twig'

sancho_app_about:
    path: /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'SanchoAppBundle:StaticPages:about.html.twig'

sancho_app_contact:
    path: /contact
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'SanchoAppBundle:StaticPages:contact.html.twig'

sancho_app_user:
    resource: "@SanchoAppBundle/Controller/UserController.php"
    type: annotation
