parameters:
#    sancho_app.example.class: Sancho\AppBundle\Example

services:
    sancho.twig.sancho_app_extension:
        class: Sancho\AppBundle\Twig\SanchoAppExtension
        tags:
            - { name: twig.extension }
